# Generated by Django 5.0.4 on 2024-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroom',
            name='former_signature',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='answer_cid',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='exam_cid',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='mentor_signature',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='student_signature',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
