# Generated by Django 5.0.4 on 2024-06-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_alter_examroom_former_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='mentor_id',
        ),
        migrations.DeleteModel(
            name='ExamRoom',
        ),
        migrations.DeleteModel(
            name='RoomDetails',
        ),
    ]
