# Generated by Django 5.0.4 on 2024-05-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
        ('Member', '0008_alter_myuser_userid_alter_usercommunity_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Member',
            field=models.ManyToManyField(related_name='groups_joined', through='Community.CommunityMember', to='Member.myuser'),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.myuser'),
        ),
        migrations.AlterField(
            model_name='communitycerti',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.myuser'),
        ),
        migrations.AlterField(
            model_name='communitydoc',
            name='created_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.myuser'),
        ),
        migrations.AlterField(
            model_name='communityformer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.myuser'),
        ),
        migrations.AlterField(
            model_name='communityhistory',
            name='updated_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.myuser'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.myuser'),
        ),
    ]
