# Generated by Django 5.0.4 on 2024-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_alter_community_member_alter_community_created_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitydoc',
            name='path',
        ),
        migrations.AddField(
            model_name='communitydoc',
            name='doc_cid',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
