# Generated by Django 5.0.3 on 2024-06-04 15:27

import Community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_remove_communitydoc_path_communitydoc_doc_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydoc',
            name='price',
            field=models.IntegerField(default=0, validators=[Community.models.validate_no_negative]),
        ),
    ]
