# Generated by Django 5.0.4 on 2024-06-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_remove_communitydoc_path_communitydoc_doc_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='Member',
        ),
        migrations.DeleteModel(
            name='CommunityMember',
        ),
    ]
