# Generated by Django 5.0.4 on 2024-06-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_remove_community_member_delete_communitymember'),
        ('Community', '0007_question_answer_delete_questions'),
    ]

    operations = [
    ]
