# Generated by Django 5.0.4 on 2024-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_remove_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
