# Generated by Django 5.0.3 on 2024-06-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0011_myuser_walletadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='MetamarskID',
        ),
    ]
