# Generated by Django 5.0.3 on 2024-06-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0012_remove_myuser_metamaskid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='WalletAdress',
            new_name='WalletAddress',
        ),
    ]
