# Generated by Django 5.0.4 on 2024-06-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0011_alter_usercommunity_user_id'),
        ('Member', '0015_alter_myuser_userid'),
    ]

    operations = [
    ]
